import { spawnSync } from "node:child_process";
import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { createGitHubClient } from "@publira/github";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import type {
  Sandbox,
  SandboxCommand,
  SandboxRunner,
} from "../sandbox-runner.ts";
import {
  REGENERATION_COMMIT_SUBJECT,
  regenerateGeneratedOutput,
  summarizeRegenerationResult,
} from "./regenerate-generated-output.ts";
import type { RegenerateGeneratedOutputResult } from "./regenerate-generated-output.ts";

const BOT = "chachamaru-bot[bot]";
const BRANCH = "renovate/buf";
const repository = "/repos/publira/publira";

// Where the job checks the pull request out in its sandbox.
const SANDBOX_WORKTREE = "/tmp/repository";

// Bytes that are not UTF-8, as in an image a generator writes.
const IMAGE = Buffer.from([0x00, 0x01, 0xff, 0xfe, 0x0a]);

const CONFIG = `triggers:
  - buf.gen.yaml
  - .github/workflows/ci.yml
workflowEnv: .github/workflows/ci.yml
setup:
  - printf '#!/bin/sh\\necho "generated by gen $GEN_VERSION from $(cat buf.gen.yaml)"\\n' > "$HOME/.local/bin/gen" && chmod +x "$HOME/.local/bin/gen"
command: ./gen.sh
paths:
  - gen/**
`;

const WORKFLOW = `name: CI
env:
  GEN_VERSION: 2.0.0
on: pull_request
`;

// What the generator writes: the output of the tool the setup installed, an
// executable, an image, and a file outside the generated paths. It deletes
// a file it no longer generates.
const GENERATOR = `#!/bin/sh
set -e
mkdir -p gen
gen > gen/api.txt
printf '#!/bin/sh\\n' > gen/run.sh
chmod +x gen/run.sh
printf '\\000\\001\\377\\376\\n' > gen/image.bin
rm -f gen/old.txt
echo touched > notes.txt
`;

const runGit = (cwd: string, ...args: string[]) => {
  const result = spawnSync("git", args, { cwd, encoding: "utf-8" });
  if (result.status !== 0) {
    throw new Error(`git ${args.join(" ")}: ${result.stderr}`);
  }
  return result.stdout.trim();
};

const write = (root: string, file: string, content: string | Buffer) => {
  mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
  writeFileSync(path.join(root, file), content);
};

const commitAll = (root: string, message: string) => {
  runGit(root, "add", "--all");
  runGit(
    root,
    "-c",
    "user.name=Test",
    "-c",
    "user.email=test@example.com",
    "commit",
    "--quiet",
    `--message=${message}`
  );
  return runGit(root, "rev-parse", "HEAD");
};

interface Fixture {
  /** The origin the sandbox fetches, standing in for GitHub. */
  origin: string;
  baseSha: string;
  /** Renovate's commit, which bumps the generator. */
  headSha: string;
}

/**
 * A repository whose generated output came from version 1, and a Renovate
 * commit on top that bumps the generator to version 2 without regenerating.
 */
const createFixture = (root: string): Fixture => {
  const origin = path.join(root, "origin");
  mkdirSync(origin);
  runGit(origin, "init", "--quiet", "--initial-branch=main");
  write(origin, "buf.gen.yaml", "v1");
  write(origin, ".github/workflows/ci.yml", WORKFLOW);
  write(origin, "gen.sh", GENERATOR);
  chmodSync(path.join(origin, "gen.sh"), 0o755);
  write(origin, "gen/api.txt", "generated by gen 1.0.0 from v1\n");
  write(origin, "gen/old.txt", "obsolete\n");
  const baseSha = commitAll(origin, "Initial commit");
  write(origin, "buf.gen.yaml", "v2");
  const headSha = commitAll(origin, "chore(deps): update buf.gen.yaml");
  return { baseSha, headSha, origin };
};

interface LocalSandboxOptions {
  root: string;
  origin: string;
  fetchExitCode?: number;
}

/**
 * A sandbox that runs the job's commands on this machine, in a directory of
 * its own, with a home of its own: the fetch reads the local origin.
 */
const localSandbox = ({
  root,
  origin,
  fetchExitCode = 0,
}: LocalSandboxOptions) => {
  const worktree = path.join(root, "sandbox", "repository");
  const home = path.join(root, "sandbox", "home");
  mkdirSync(home, { recursive: true });
  const commands: SandboxCommand[] = [];
  const localize = (value: string) =>
    value.replaceAll(SANDBOX_WORKTREE, worktree);

  const sandbox: Sandbox = {
    run(command) {
      commands.push(command);
      const args = (command.args ?? []).map(localize);

      if (
        command.cmd === "git" &&
        args.includes("fetch") &&
        fetchExitCode !== 0
      ) {
        return Promise.resolve({
          exitCode: fetchExitCode,
          stderr: "fatal: repository not found",
          stdout: "",
        });
      }
      const result = spawnSync(
        command.cmd,
        args.map((arg) =>
          arg.startsWith("https://github.com/") ? `file://${origin}` : arg
        ),
        {
          cwd: command.cwd === undefined ? undefined : localize(command.cwd),
          encoding: "utf-8",
          env: { ...process.env, HOME: home, ...command.env },
          maxBuffer: 64 * 1024 * 1024,
        }
      );
      return Promise.resolve({
        exitCode: result.status ?? 1,
        stderr: result.stderr,
        stdout: result.stdout,
      });
    },
  };
  let started = 0;
  const runner: SandboxRunner = (task) => {
    started += 1;
    return task(sandbox);
  };

  return { commands, runner, started: () => started, worktree };
};

interface GitHubOptions {
  fixture: Fixture;
  private?: boolean;
  user?: { login: string; type: string };
  /** The base branch's declaration; `null` for none. */
  config?: string | null;
  /** The files the pull request changes. */
  changed?: readonly string[];
  /** The head commit's author and message, as the comparison lists it. */
  headCommit?: { author: string; message: string };
  /** Whether the branch moved, so a fast-forward fails. */
  moved?: boolean;
}

const file = (content: string) =>
  Response.json({
    content: Buffer.from(content).toString("base64"),
    encoding: "base64",
    type: "file",
  });

const notFound = () => Response.json({ message: "Not Found" }, { status: 404 });

// Answers the GitHub API and records the writes.
const fakeGitHub = ({
  fixture,
  private: isPrivate = false,
  user = { login: "renovate[bot]", type: "Bot" },
  config = CONFIG,
  changed = ["buf.gen.yaml"],
  headCommit = {
    author: "renovate[bot]",
    message: "chore(deps): update buf.gen.yaml",
  },
  moved = false,
}: GitHubOptions) => {
  const writes: { route: string; body: unknown }[] = [];

  const fetchImpl = vi.fn<typeof fetch>((input, init) => {
    const url = new URL(String(input));
    const method = init?.method ?? "GET";
    const route = `${method} ${decodeURIComponent(url.pathname)}`;
    const ref = url.searchParams.get("ref");

    if (method !== "GET") {
      writes.push({ body: JSON.parse(String(init?.body)), route });
    }

    switch (route) {
      case `GET ${repository}/pulls/31`: {
        return Promise.resolve(
          Response.json({
            base: {
              ref: "main",
              repo: { full_name: "publira/publira", private: isPrivate },
              sha: fixture.baseSha,
            },
            head: {
              ref: BRANCH,
              repo: { full_name: "publira/publira" },
              sha: fixture.headSha,
            },
            number: 31,
            state: "open",
            user,
          })
        );
      }
      case `GET ${repository}/contents/.chachamaru/regenerate.yml`: {
        return Promise.resolve(
          config === null || ref !== fixture.baseSha ? notFound() : file(config)
        );
      }
      case `GET ${repository}/contents/.github/workflows/ci.yml`: {
        return Promise.resolve(
          ref === fixture.headSha ? file(WORKFLOW) : notFound()
        );
      }
      case `GET ${repository}/compare/${fixture.baseSha}...${fixture.headSha}`: {
        return Promise.resolve(
          Response.json({
            commits: [
              {
                author: { login: headCommit.author },
                commit: { message: headCommit.message },
                sha: fixture.headSha,
              },
            ],
            files: changed.map((filename) => ({ filename })),
            merge_base_commit: { sha: fixture.baseSha },
          })
        );
      }
      case `GET ${repository}/git/commits/${fixture.headSha}`: {
        return Promise.resolve(Response.json({ tree: { sha: "head-tree" } }));
      }
      case `POST ${repository}/git/blobs`: {
        return Promise.resolve(Response.json({ sha: "image-blob" }));
      }
      case `POST ${repository}/git/trees`: {
        return Promise.resolve(Response.json({ sha: "new-tree" }));
      }
      case `POST ${repository}/git/commits`: {
        return Promise.resolve(Response.json({ sha: "new-commit" }));
      }
      case `PATCH ${repository}/git/refs/heads/${BRANCH}`: {
        return Promise.resolve(
          moved
            ? Response.json(
                { message: "Update is not a fast forward" },
                { status: 422 }
              )
            : Response.json({})
        );
      }
      default: {
        return Promise.resolve(notFound());
      }
    }
  });

  return { octokit: createGitHubClient({ fetch: fetchImpl }), writes };
};

const location = {
  botLogin: BOT,
  // A public repository is fetched without a token.
  createReadToken: () => Promise.reject(new Error("No token for a public one")),
  owner: "publira",
  pullNumber: 31,
  repo: "publira",
};

const run = (
  github: ReturnType<typeof fakeGitHub>,
  sandbox: ReturnType<typeof localSandbox>,
  options: { dryRun?: boolean; createReadToken?: () => Promise<string> } = {}
) =>
  regenerateGeneratedOutput({
    ...location,
    ...options,
    octokit: github.octokit,
    sandbox: sandbox.runner,
  });

describe(regenerateGeneratedOutput, () => {
  let root: string;
  let fixture: Fixture;

  beforeEach(() => {
    root = mkdtempSync(path.join(tmpdir(), "regenerate-generated-output-"));
    fixture = createFixture(root);
  });

  afterEach(() => {
    rmSync(root, { force: true, recursive: true });
  });

  it("plans the commit in a dry run", async () => {
    const github = fakeGitHub({ fixture });
    const sandbox = localSandbox({ origin: fixture.origin, root });

    await expect(run(github, sandbox, { dryRun: true })).resolves.toStrictEqual(
      {
        headSha: fixture.headSha,
        ignoredPaths: ["notes.txt"],
        paths: ["gen/api.txt", "gen/image.bin", "gen/old.txt", "gen/run.sh"],
        status: "would-commit",
      } satisfies RegenerateGeneratedOutputResult
    );
    expect(github.writes).toStrictEqual([]);
    // The setup installed the version the head's workflow pins.
    expect(
      readFileSync(path.join(sandbox.worktree, "gen/api.txt"), "utf-8")
    ).toBe("generated by gen 2.0.0 from v2\n");
  });

  it("commits the generated files with their modes on top of the head", async () => {
    const github = fakeGitHub({ fixture });
    const sandbox = localSandbox({ origin: fixture.origin, root });

    await expect(run(github, sandbox)).resolves.toStrictEqual({
      commitSha: "new-commit",
      headSha: fixture.headSha,
      ignoredPaths: ["notes.txt"],
      paths: ["gen/api.txt", "gen/image.bin", "gen/old.txt", "gen/run.sh"],
      status: "committed",
    } satisfies RegenerateGeneratedOutputResult);

    expect(github.writes).toStrictEqual([
      {
        body: { content: IMAGE.toString("base64"), encoding: "base64" },
        route: `POST ${repository}/git/blobs`,
      },
      {
        body: {
          base_tree: "head-tree",
          tree: [
            {
              content: "generated by gen 2.0.0 from v2\n",
              mode: "100644",
              path: "gen/api.txt",
              type: "blob",
            },
            {
              mode: "100644",
              path: "gen/image.bin",
              sha: "image-blob",
              type: "blob",
            },
            { mode: "100644", path: "gen/old.txt", sha: null, type: "blob" },
            {
              content: "#!/bin/sh\n",
              mode: "100755",
              path: "gen/run.sh",
              type: "blob",
            },
          ],
        },
        route: `POST ${repository}/git/trees`,
      },
      {
        body: {
          message: `${REGENERATION_COMMIT_SUBJECT}\n\nRan \`./gen.sh\` on ${fixture.headSha}.`,
          parents: [fixture.headSha],
          tree: "new-tree",
        },
        route: `POST ${repository}/git/commits`,
      },
      {
        body: { force: false, sha: "new-commit" },
        route: `PATCH ${repository}/git/refs/heads/${BRANCH}`,
      },
    ]);
  });

  it("writes nothing when the generated output is current", async () => {
    write(fixture.origin, "gen.sh", "#!/bin/sh\necho touched > notes.txt\n");
    fixture.headSha = commitAll(fixture.origin, "Generate nothing");
    const github = fakeGitHub({ fixture });
    const sandbox = localSandbox({ origin: fixture.origin, root });

    await expect(run(github, sandbox)).resolves.toStrictEqual({
      headSha: fixture.headSha,
      ignoredPaths: ["notes.txt"],
      status: "unchanged",
    });
    expect(github.writes).toStrictEqual([]);
  });

  it("leaves a branch that moved to its push", async () => {
    const github = fakeGitHub({ fixture, moved: true });
    const sandbox = localSandbox({ origin: fixture.origin, root });

    await expect(run(github, sandbox)).resolves.toMatchObject({
      status: "head-moved",
    });
  });

  it.each([
    [
      "Renovate did not open the pull request",
      { user: { login: "ykzts", type: "User" } },
    ],
    ["the base branch has no .chachamaru/regenerate.yml", { config: null }],
    [
      "the pull request changes no file that calls for a regeneration",
      { changed: ["package.json"] },
    ],
    [
      "the head is the bot's regeneration already",
      {
        headCommit: {
          author: BOT,
          message: `${REGENERATION_COMMIT_SUBJECT}\n\nRan.`,
        },
      },
    ],
  ])("skips when %s", async (reason, options) => {
    const github = fakeGitHub({ fixture, ...options });
    const sandbox = localSandbox({ origin: fixture.origin, root });

    await expect(run(github, sandbox)).resolves.toStrictEqual({
      headSha: fixture.headSha,
      reason,
      status: "skipped",
    });
    expect(sandbox.started()).toBe(0);
  });

  it("skips an invalid declaration", async () => {
    const github = fakeGitHub({ config: "command: make\n", fixture });
    const sandbox = localSandbox({ origin: fixture.origin, root });

    await expect(run(github, sandbox)).resolves.toMatchObject({
      reason: expect.stringContaining(".chachamaru/regenerate.yml"),
      status: "skipped",
    });
    expect(sandbox.started()).toBe(0);
  });

  it.each([
    [
      "setup",
      CONFIG.replace(
        /setup:\n {2}- .*\n/u,
        "setup:\n  - echo no tool >&2; exit 3\n"
      ),
      3,
    ],
    ["command", CONFIG.replace("./gen.sh", "echo broken >&2; exit 4"), 4],
  ])(
    "leaves the pull request alone when the %s fails",
    async (step, config, exitCode) => {
      const github = fakeGitHub({ config, fixture });
      const sandbox = localSandbox({ origin: fixture.origin, root });

      await expect(run(github, sandbox)).resolves.toStrictEqual({
        exitCode,
        headSha: fixture.headSha,
        output: expect.stringContaining(
          step === "setup" ? "no tool" : "broken"
        ),
        status: "failed",
        step,
      });
      expect(github.writes).toStrictEqual([]);
    }
  );

  it("leaves the pull request alone when the fetch fails", async () => {
    const github = fakeGitHub({ fixture });
    const sandbox = localSandbox({
      fetchExitCode: 128,
      origin: fixture.origin,
      root,
    });

    await expect(run(github, sandbox)).resolves.toMatchObject({
      exitCode: 128,
      output: "fatal: repository not found",
      status: "failed",
      step: "fetch",
    });
  });

  it("fetches a private repository with a read token it does not store", async () => {
    const github = fakeGitHub({ fixture, private: true });
    const sandbox = localSandbox({ origin: fixture.origin, root });

    await run(github, sandbox, {
      createReadToken: () => Promise.resolve("read-token"),
      dryRun: true,
    });

    const fetch = sandbox.commands.find(({ args }) => args?.includes("fetch"));
    expect(fetch?.args?.slice(0, 2)).toStrictEqual([
      "-c",
      `http.extraHeader=Authorization: Basic ${Buffer.from("x-access-token:read-token").toString("base64")}`,
    ]);
    expect(
      readFileSync(path.join(sandbox.worktree, ".git/config"), "utf-8")
    ).not.toContain("extraHeader");
    // Nothing but the fetch saw the token.
    expect(
      sandbox.commands.filter((command) =>
        JSON.stringify(command).includes(
          Buffer.from("x-access-token:read-token").toString("base64")
        )
      )
    ).toStrictEqual([fetch]);
  });

  it("fetches a public repository anonymously", async () => {
    const github = fakeGitHub({ fixture });
    const sandbox = localSandbox({ origin: fixture.origin, root });

    await run(github, sandbox, { dryRun: true });

    expect(
      sandbox.commands.find(({ args }) => args?.includes("fetch"))?.args
    ).toStrictEqual([
      "-C",
      SANDBOX_WORKTREE,
      "fetch",
      "--quiet",
      "--depth=1",
      "https://github.com/publira/publira.git",
      fixture.headSha,
    ]);
  });
});

describe(summarizeRegenerationResult, () => {
  it("logs a failure without the file contents", () => {
    expect(
      summarizeRegenerationResult({
        exitCode: 1,
        headSha: "head",
        output: "error",
        status: "failed",
        step: "command",
      })
    ).toStrictEqual({
      commit: undefined,
      exitCode: 1,
      headSha: "head",
      ignoredPaths: undefined,
      modelInvoked: false,
      output: "error",
      paths: undefined,
      reason: undefined,
      status: "failed",
      step: "command",
    });
  });
});
